#!/usr/bin/env bash
# scripts/build-magenta-dsp-bundle.sh
# ---------------------------------------------------------------
# Assembles dist-hf/<tag>/ from the SIBLING repo
# ~/Documents/autodashboard/magenta-dsp-procedural/ — that's where
# the actual Magenta.js DrumRNN / MelodyInterpolator / TrioGenerator
# code lives. This repo (sainted-word-records) only orchestrates the
# push.
#
# USAGE
#   bash scripts/build-magenta-dsp-bundle.sh [--tag v0.1.0] [--apply]
#
# FLAGS
#   --tag <vX.Y.Z>   Override the bundle tag (default: package.json#version)
#   --apply          Write to dist-hf/. Default --dry-run: prints the plan
#                    and exits 0 without touching disk.
#   --src <path>     Override source path (default: sibling magenta-dsp repo).
#
# OUTPUT
#   dist-hf/<tag>/
#     README.md            (HF model card with license YAML frontmatter)
#     LICENSE              (inherited from sainted-word-records, MIT)
#     INFERENCE.md         (how to load & run each module)
#     MANIFEST.json        (auto-generated, lists every file + size)
#     .hfignore            (mirrors .gitignore plus Hub-specific excludes)
#     01-drum-rnn/
#     02-melody-interpolator/
#     03-trio-generator/
#     debug-*.mjs          (smoke / verify scripts, useful for Hub users)
#     test-*.mjs
#     test-*.html
#     verify_puppeteer.mjs
#
# NEVER INCLUDED (heavy / private / not part of the model)
#     node_modules/        (29 MB; references Google CDN at runtime, not
#                           needed at rest)
#     package-lock.json    (regenerated by users on `npm install`)
#     *.DS_Store
#     .env / .env.local
# ---------------------------------------------------------------
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TAG=""
APPLY=0
SRC="${MAGENTA_DSP_SRC:-$HOME/Documents/autodashboard/magenta-dsp-procedural}"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --tag)  TAG="$2"; shift 2 ;;
    --apply) APPLY=1; shift ;;
    --src)  SRC="$2"; shift 2 ;;
    -h|--help) sed -n '2,40p' "$0"; exit 0 ;;
    *) echo "unknown flag: $1" >&2; exit 64 ;;
  esac
done

# Resolve tag from package.json if not provided
if [[ -z "$TAG" ]]; then
  if command -v jq >/dev/null 2>&1; then
    TAG="v$(jq -r '.version' "$REPO_ROOT/package.json")"
  else
    TAG="v$(node -e 'process.stdout.write(require("./package.json").version)')"
  fi
fi

OUT="$REPO_ROOT/dist-hf/$TAG"
echo "[hf-bundle] src  = $SRC"
echo "[hf-bundle] tag  = $TAG"
echo "[hf-bundle] out  = $OUT"
echo "[hf-bundle] mode = $([[ $APPLY -eq 1 ]] && echo APPLY || echo DRY-RUN)"

# ---- preflight ----
if [[ ! -d "$SRC" ]]; then
  if [[ "${SWR_HF_BUNDLE_REQUIRED:-0}" == "1" ]]; then
    # Hard failure for caller opt-in (apply mode / CI / api/hf-upload). Set
    # SWR_HF_BUNDLE_REQUIRED=1 to enforce the source exists.
    echo "[hf-bundle] ERROR: source not found at $SRC" >&2
    echo "[hf-bundle] tip:  pass --src /path/to/magenta-dsp-procedural" >&2
    exit 2
  fi
  # Default: skip with an explicit notice so `npm run check` doesn't break
  # on machines / CI runners without the sibling repo. The user-facing
  # publish flow (api/hf-upload.js, scripts/push-…) still requires it.
  echo "[hf-bundle] skip: source not found at $SRC"
  echo "[hf-bundle] (set SWR_HF_BUNDLE_REQUIRED=1 to enforce)"
  exit 0
fi

if [[ ! -f "$SRC/01-drum-rnn/index.html" ]] \
   || [[ ! -f "$SRC/02-melody-interpolator/index.html" ]] \
   || [[ ! -f "$SRC/03-trio-generator/index.html" ]]; then
  echo "[hf-bundle] ERROR: expected 0X-* demo HTMLs missing in $SRC" >&2
  exit 3
fi

# Files & dirs to copy (relative to $SRC)
COPY_ITEMS=(
  01-drum-rnn
  02-melody-interpolator
  03-trio-generator
  index.html
)
COPY_GLOBS=(
  "debug-*.mjs"
  "test-*.mjs"
  "test-*.html"
  "verify_puppeteer.mjs"
  "package.json"
)

# ---- plan ----
echo ""
echo "[hf-bundle] plan:"
printf "  cp -r %s\n" "${COPY_ITEMS[*]}"
printf "  cp     %s\n" "${COPY_GLOBS[*]}"
echo "  + README.md (HF model card with license YAML)"
echo "  + INFERENCE.md"
echo "  + LICENSE"
echo "  + MANIFEST.json"
echo "  + .hfignore"

if [[ $APPLY -eq 0 ]]; then
  echo ""
  echo "[hf-bundle] DRY-RUN — pass --apply to write to $OUT"
  echo "[hf-bundle] next: hf upload kaidjuric/magenta-dsp-procedural $OUT/ . --repo-type model --commit-message \"release: $TAG\""
  exit 0
fi

# ---- apply ----
mkdir -p "$OUT"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

# Copy items
for item in "${COPY_ITEMS[@]}"; do
  cp -R "$SRC/$item" "$TMP/"
done
for pat in "${COPY_GLOBS[@]}"; do
  for f in $SRC/$pat; do
    [[ -e "$f" ]] || continue
    cp "$f" "$TMP/"
  done
done

# LICENSE
if [[ ! -f "$TMP/LICENSE" ]]; then
  if [[ -f "$REPO_ROOT/LICENSE" ]]; then
    cp "$REPO_ROOT/LICENSE" "$TMP/LICENSE"
  else
    echo "[hf-bundle] WARN: no LICENSE in repo root; writing MIT stub" >&2
    cat > "$TMP/LICENSE" <<'EOF'
MIT License — see https://huggingface.co/kaidjuric/magenta-dsp-procedural
EOF
  fi
fi

# README.md — HF model card (YAML frontmatter REQUIRED on first push)
cat > "$TMP/README.md" <<EOF
---
license: mit
tags:
  - magenta
  - music-generation
  - drummernn
  - melodyrnn
  - musicvae
  - procedural
  - web-audio
  - browser
datasets: []
metrics: []
model_name: magenta-dsp-procedural
---

# magenta-dsp-procedural

Three procedural audio modules built on Magenta.js (TensorFlow.js):
drum pattern generation, melody interpolation, and trio (drums + bass +
melody) co-generation. Each module is a single self-contained HTML page
that runs in any modern browser — no server, no API key.

Built and maintained by Sainted Word Records as a companion model bundle
for the algorithmic audio-reactive video engine.

## Modules

| # | Module | What it does |
|---|--------|--------------|
| 01 | \`01-drum-rnn/\`            | Drum pattern generation via MusicRNN |
| 02 | \`02-melody-interpolator/\` | Latent-space interpolation between two melodies (MusicVAE) |
| 03 | \`03-trio-generator/\`      | Co-generates drum + bass + melody trio (MusicVAE trio) |

## Run locally

\`\`\`
git clone https://huggingface.co/kaidjuric/magenta-dsp-procedural
cd magenta-dsp-procedural
python3 -m http.server 8000
open http://localhost:8000/01-drum-rnn/
\`\`\`

Or open any \`01-*/index.html\` directly in a modern browser — the pages
load Magenta.js from the Google CDN at runtime.

## Verify

Each module has a \`test-*.mjs\` script. See \`INFERENCE.md\` for details.

## License

MIT — see \`LICENSE\`.
EOF

# INFERENCE.md
cat > "$TMP/INFERENCE.md" <<'EOF'
# INFERENCE

Each module loads Magenta.js from the official Google CDN. No build step.
No server. No API key.

## Quick start (browser)

```html
<script src="https://cdn.jsdelivr.net/npm/@magenta/music@1.23.1/dist/magenta.js"></script>
```

Then open `01-drum-rnn/index.html` in any modern browser.

## Headless verify

```bash
node test-drum-rnn.mjs
```

Smoke scripts (`test-*.mjs`) use Puppeteer against the bundled `index.html`.
Install Puppeteer on demand: `npm i puppeteer`.

## Stable checkpoints

Magenta.js itself ships checkpoints — see https://storage.googleapis.com/magentadata/js/checkpoints/
The bundled HTMLs reference the canonical Magenta MusicRNN drum_kit,
MusicVAE melody, and MusicVAE trio checkpoints.

## Inference: programmatic call

```js
const drumRNN = new mm.MusicRNN('https://storage.googleapis.com/magentadata/js/checkpoints/music_rnn/drum_kit');
await drumRNN.initialize();
const seed = mm.sequences.unquantizeSequence(/* … */);
const out  = await drumRNN.continueSequence(seed, 20, 1.5);
```

## Versioning

Tags are `vX.Y.Z` matching this repo's `package.json#version`.
Each release is a fresh `hf upload` from `scripts/push-magenta-dsp-to-hf.sh`.
EOF

# .hfignore — Hub-side excludes
cat > "$TMP/.hfignore" <<'EOF'
# .hfignore — files the Hub upload should always skip.
node_modules/
*.log
.DS_Store
.env
.env.*
package-lock.json
verify-screenshots/
*.tmp
EOF

# MANIFEST.json — auto-generated inventory
node -e "
const fs = require('fs');
const path = require('path');
const root = '$TMP';
const out = { tag: '$TAG', generated_at: new Date().toISOString(), files: [] };
(function walk(dir, base) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const rel = path.posix.join(base, e.name);
    const full = path.join(dir, e.name);
    if (e.isDirectory()) {
      if (['node_modules', '.git'].includes(e.name)) continue;
      walk(full, rel);
    } else {
      const st = fs.statSync(full);
      out.files.push({ path: rel, bytes: st.size });
    }
  }
})(root, '');
fs.writeFileSync(path.join(root, 'MANIFEST.json'), JSON.stringify(out, null, 2));
"

# Move tmp -> out
rm -rf "$OUT"
mkdir -p "$(dirname "$OUT")"
mv "$TMP" "$OUT"

SIZE=$(du -sh "$OUT" | awk '{print $1}')
COUNT=$(node -e 'process.stdout.write(String(JSON.parse(require("fs").readFileSync("'"$OUT"'/MANIFEST.json","utf8")).files.length))')
echo ""
echo "[hf-bundle] wrote $OUT ($SIZE, $COUNT files)"
echo "[hf-bundle] next: bash scripts/push-magenta-dsp-to-hf.sh --tag $TAG"
