// api/email-book.js — Vercel serverless: emails the compiled exercise
// book PDF via Resend with an attachment. The PDF lives in the repo at
// /books/beginner-trumpet-vol1.pdf (static file served by Vercel).
//
// GET /api/email-book?to=kai.djuric@gmail.com
//   -> { ok: true, transport: 'resend' } on success
//   -> 503 if RESEND_API_KEY unset, 400 if no to=, 500 on send failure
//
// Uses the same Resend transport as api/_lib/email.js but adds the
// attachments field (the shared lib's resendDeliver doesn't carry
// attachments yet).

const fs = require('fs');
const path = require('path');

const FROM = process.env.SWR_FROM_EMAIL || 'SWR <noreply@saintedwordrecords.com>';
const REPLY_TO = process.env.SWR_REPLY_TO_EMAIL || '';

module.exports = async function handler(req, res) {
  // CORS for the storefront origin.
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, OPTIONS');
  if (req.method === 'OPTIONS') return res.status(204).end();

  const apiKey = process.env.RESEND_API_KEY;
  if (!apiKey) {
    return res.status(503).json({ ok: false, error: 'RESEND_API_KEY not set' });
  }

  const to = (req.query.to || '').trim();
  if (!to) {
    return res.status(400).json({ ok: false, error: 'missing to= email' });
  }

  try {
    const pdfPath = path.join(process.cwd(), 'books', 'beginner-trumpet-vol1.pdf');
    const pdfBytes = fs.readFileSync(pdfPath);
    const payload = {
      from: FROM,
      to,
      subject: 'Beginner Trumpet Exercises Vol 1 — your book PDF',
      text:
        'Here is your compiled exercise book PDF (12 exercises with chord charts and practice notes).\n\n' +
        'Generated by the Harmonic Study Engine.\n\n' +
        'kai.djuric@gmail.com',
      attachments: [
        {
          filename: 'beginner-trumpet-vol1.pdf',
          content: pdfBytes.toString('base64'),
        },
      ],
    };
    if (REPLY_TO) payload.reply_to = REPLY_TO;

    const r = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${apiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(payload),
      signal: AbortSignal.timeout(15000),
    });
    if (!r.ok) {
      const txt = await r.text();
      return res.status(500).json({ ok: false, error: `resend ${r.status}: ${txt}` });
    }
    return res.status(200).json({ ok: true, transport: 'resend' });
  } catch (e) {
    return res.status(500).json({ ok: false, error: String(e.message || e) });
  }
};